services:
  firefox:
    image: seleniarm/standalone-firefox:v4.3.0-20220709
    ports:
      - "4444:4444"
    links:
      - "mock-server:recaptcha-v3-test.com"
  chrome:
    image: seleniarm/standalone-chromium:v4.3.0-20220709
    ports:
      - "4445:4444"
    links:
      - "mock-server:recaptcha-v3-test.com"
    volumes:
      - "path/to/local/profile:/tmp/chrome/profile"
  mock-server:
    image: sheva0914/mock-server:v2.1-06092022
    ports:
      - "8000:8000"
